name: Npm Publish
on:
 release:
 types: [updated]
jobs:
  build:
   runs-on: ubuntu-latest
    steps:
      — uses: actions/checkout@v2
      — uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      — run: npm ci
      — run: npm run semantic-release
        env:
         NODE_AUTH_TOKEN: ${{secrets.NPM_TKOEN}}